server:
  port: 3001
  servlet:
    context-path: /
  compression:
    enabled: true

spring:
  application:
    name: elderdiet-backend-java

  data:
    mongodb:
      uri: mongodb://localhost:27017/elderdiet
      auto-index-creation: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  profiles:
    active: dev

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# JWT配置
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-this-in-production}
  expiration: ${JWT_EXPIRES_IN:604800} # 7天 (秒)

# 日志配置
logging:
  level:
    com.elderdiet: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/elderdiet-backend.log

# Actuator监控端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: when-authorized

# AI API配置
ai:
  api:
    url: https://api2.aigcbest.top/v1/chat/completions
    key: ${QIANDUODUO_API_KEY:your-api-key-here}
    #claude-3-5-haiku-latest，gpt-4o，gpt-4o-mini，gemini-1.5-flash
    model: gemini-1.5-flash
    temperature: 0.7

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:oss-cn-shanghai.aliyuncs.com}
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID:your-access-key-id}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:your-access-key-secret}
    bucket-name: ${ALIYUN_OSS_BUCKET_NAME:elder-diet}
    base-url: ${ALIYUN_OSS_BASE_URL:https://elder-diet.oss-cn-shanghai.aliyuncs.com}
    upload-path: ${ALIYUN_OSS_UPLOAD_PATH:diet-images/}

# 应用信息
info:
  app:
    name: ElderDiet Backend Java
    description: 老年人膳食助手后端服务
    version: 1.0.0
    developer: ElderDiet Team

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      #uri: mongodb://${MONGODB_USER:devUser}:${MONGODB_PASSWORD}@localhost:27017/elderdiet_dev
      uri: mongodb://${MONGODB_USER:devUser}:${MONGODB_PASSWORD}@8.153.204.247:27017/elderdiet_dev

logging:
  level:
    root: INFO
    com.elderdiet: DEBUG

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod

  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:prodUser}:${MONGODB_PASSWORD}@localhost:27017/elderdiet_prod

logging:
  level:
    root: WARN
    com.elderdiet: INFO
